name: Test Astro Website
description: |
  This workflow tests your Astro site.
  It runs linting and other checks to ensure code quality.

runs:
  using: "composite"
  steps:
    - name: Checkout your repository using git
      uses: actions/checkout@v5
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: lib/website/.nvmrc
        cache: "yarn"
        cache-dependency-path: lib/website/yarn.lock
    - name: Install dependencies
      shell: bash
      working-directory: lib/website
      run: |
        yarn install --frozen-lockfile
    - name: Run Astro Lint
      shell: bash
      working-directory: lib/website
      run: |
        yarn lint
